# Site settings
title: 光赢不输的程序猿
email: markta31@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  夜空中最耀的星，记录我寻觅宝藏留下的脚印。我是mark311。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mark311.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  mark311

# Build settings
markdown: kramdown
